"""Do the athermal cells land on Kim and Kamrin's published master curve?

WHY THIS EXISTS.  Sec. III A establishes that the flow reproduces mu(I) by
comparing plateau values against da Cruz et al.  That is a check on one number.
Kim and Kamrin publish explicit fits for f(I) itself (Supplemental Material,
Sec. S2), so the whole relation mu*Theta^p = f(I) can be evaluated at our
operating point rather than just its plateau.  The athermal cells are the
like-for-like data: their flows are unforced, with Theta generated by the shear,
and so are these.

THREE CONVERSIONS STAND BETWEEN THE TWO PAPERS.  Getting any of them wrong
would manufacture a disagreement.

  1. Inertial number, 2D.  Theirs is gammadot*sqrt(m/P); ours is the
     dimension-independent gammadot*d*sqrt(rho/P).  For disks m = rho*pi*d^2/4,
     so theirs is sqrt(pi/4) = 0.886 times ours.  (In 3D they use
     gammadot*d*sqrt(rho/P) as well, so 3D would need no conversion.)

  2. Temperature.  Theirs is dimensionless, Theta_KK = rho*T/P with T the
     velocity-fluctuation temperature; ours is Theta = m<dv^2>/D and is NOT
     divided by pressure (Table I).  With <dv^2> = D*dvx^2 under isotropy,
     Theta_KK = rho*Theta/(m*P).

  3. Which component.  They take T = dvx^2, one diagonal component, because in
     their geometry the components differ near rigid walls.  Ours is the trace
     average.  Sheared packings are not exactly isotropic in the fluctuations,
     so this is the one conversion that cannot be closed from either paper.
     Its size is reported below as a sensitivity rather than assumed away.

A ratio of 1 means the athermal cells sit on their published curve.

Usage:  python3 kk_master.py
"""
import glob
import os
import re
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import nfit

RX = r'log\.nt_g(?P<g>[0-9.eE+-]+)_e(?P<e>[0-9.]+)_mu(?P<mu>[0-9.]+)_s(?P<s>\d+)$'

# Supplemental Material Sec. S2, disks.  f(I) = A I^a + B I^b.
KK_F = {0.1: (0.17, 0.18, 0.47, 0.75),
        0.4: (0.21, 0.17, 0.55, 0.75)}
KK_P = 1.0 / 8.0                      # their fitted exponent for disks
RHO, D_DIM = 1.0, 2
MASS = RHO * np.pi * 0.25             # disk of unit diameter, our units
I_CONV = np.sqrt(np.pi / 4.0)         # our I -> their I, 2D


def f_kk(I, mu_p):
    A, a, B, b = KK_F[mu_p]
    return A * I ** a + B * I ** b


def cells(d='sweep_nothermo2'):
    out = {}
    for p in glob.glob(f'{d}/log.nt_*'):
        m = re.match(RX, os.path.basename(p))
        if not m:
            continue
        q = nfit.parse_log(p)
        if not q or 'Pm' not in q or q['Theta'] <= 0:
            continue
        out.setdefault((float(m.group('e')), float(m.group('mu')),
                        float(m.group('g'))), []).append(q)
    return out


def main():
    C = cells()
    if not C:
        print('sweep_nothermo2 not unpacked; run this beside the log archive.')
        return 1
    print('=' * 96)
    print('THE ATHERMAL CELLS AGAINST KIM AND KAMRIN\'S PUBLISHED f(I), 2D DISKS')
    print('=' * 96)
    print(f'  their p = {KK_P:.4f};  I conversion x{I_CONV:.3f};  '
          f'Theta_KK = rho*Theta/(m*P) with m = {MASS:.4f}\n')
    print(f'  {"mu_g":>6}{"gdot":>10}{"mu":>8}{"our I":>11}{"their I":>11}'
          f'{"their Th":>11}{"mu*Th^p":>10}{"f(I)":>9}{"ratio":>8}   fit used')
    rows = []
    for k in sorted(C):
        e, mg, g = k
        if abs(e - 0.5) > 1e-9:                    # baseline restitution only
            continue
        r = C[k]
        mu = float(np.mean([x['mu'] for x in r]))
        th = float(np.mean([x['Theta'] for x in r]))
        I = float(np.mean([x['I'] for x in r]))
        P = float(np.mean([x['Pm'] for x in r]))
        if mu <= 0 or I <= 0 or P <= 0:
            continue
        mu_p = min(KK_F, key=lambda v: abs(v - mg))
        Ik = I * I_CONV
        thk = RHO * th / (MASS * P)
        lhs = mu * thk ** KK_P
        rhs = f_kk(Ik, mu_p)
        print(f'  {mg:>6g}{g:>10.3e}{mu:>8.4f}{I:>11.3e}{Ik:>11.3e}'
              f'{thk:>11.3e}{lhs:>10.4f}{rhs:>9.4f}{lhs/rhs:>8.2f}   mu_p={mu_p}')
        if mg > 0:
            rows.append(lhs / rhs)

    if rows:
        a = np.array(rows)
        print(f'\n  frictional cells: ratio {a.min():.2f} to {a.max():.2f}, '
              f'median {np.median(a):.2f} over {len(a)} cells.')
        print('  The frictionless cells are listed but excluded: Kim and Kamrin')
        print('  fit no frictionless case, so there is no curve to compare to.')

    print('\n  SENSITIVITY TO THE COMPONENT CONVENTION (item 3 above).')
    print('  If their dvx^2 is instead the full trace average, Theta_KK rises')
    print(f'  by D = {D_DIM} and mu*Th^p by {D_DIM ** KK_P:.3f}, moving every')
    print('  ratio by that factor.  Any conclusion that survives both readings')
    print('  is safe; any that does not should not be quoted.')
    if rows:
        b = np.array(rows) * D_DIM ** KK_P
        print(f'  under that reading: ratio {b.min():.2f} to {b.max():.2f}, '
              f'median {np.median(b):.2f}.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
